### ISSUE TITLE
Duplicate Triggers in Gateway Discovery Template

### ISSUE THREAD

**Issue by GuillaumeHullin** [rbicelli/pfsense-zabbix-template#156]
The trigger prototypes in the 'Template pfSense Active' (Zabbix 6) for gateway discovery appear to be duplicated. Each pair of triggers has slightly different expressions, primarily differing by using the last value or the 3th last in the second trigger of each pair. The affected triggers are:
- **Gateway {#GATEWAY} is down**
- **Gateway {#GATEWAY} is forced down**
- **High Delay on gateway {#GATEWAY}**
- **High packet Loss on {#GATEWAY}**
- **Packet Loss on {#GATEWAY}**

1. Is this duplication intentional for some functional reason?
2. If not, should one of each pair of triggers be removed to prevent redundancy? (I can do the pull request)

**Comment by rbicelli** [comment]
Sorry but don't understand your concerns:

- Gateway {#GATEWAY} is down: gateway is monitored in pfsense and monitoring is reporting that gateway is down
- Gateway {#GATEWAY} is forced down: gateway is marked down by the pfsense administrator. This raises a low-importance trigger, since is probably intentional
- High Delay on gateway {#GATEWAY}: lag is not packet loss
- High packet Loss on {#GATEWAY}: packet loss is above threshold, so critical trigger is fired
- Packet Loss on {#GATEWAY}: packet loss is under threshold, so warning trigger is fired

If you are interested only in some of that trigger, the right thing to do is disable the trigger on your pfsense host/at template level.

**Comment by GuillaumeHullin** [comment]
No, the issue is that the triggers are duplicated in the template:

Here is an example for `High Delay on gateway {#GATEWAY}`. See the following [line](https://github.com/rbicelli/pfsense-zabbix-template/blob/3b364dbd32ed78fb0380d8c41f00cc353c2e56ea/zabbix6/pfsense_active.yaml#L850C1-L860C1) 

```yaml
                - uuid: fca46e537f144ea49eca155570f8da4d
                  expression: 'last(/Template pfSense Active/pfsense.value[gw_value,{#GATEWAY},status])=2'
                  name: 'High Delay on gateway {#GATEWAY}'
                  priority: WARNING
                  description: 'Gateway is lagging'
                - uuid: faaa981f96444c90accf769c5d1949a7
                  expression: 'last(/Template pfSense Active/pfsense.value[gw_value,{#GATEWAY},status],#3)=2'
                  name: 'High Delay on gateway {#GATEWAY}'
                  priority: WARNING
                  description: 'Gateway is lagging'
```

There are two triggers for the same thing... only one is the using the last value and the other the 3rd last.
